### PR TITLE
Rename libproxy.patch to libproxy.patch.nouse

### PR DESCRIPTION
**Pull request by f1vefour**
Testing patch validity.

### CODE REVIEW

**Comment by CurlyMoo** [comment]
We'll see what happens in the next build :+1:

**Comment by f1vefour** [comment]
*crossesfingers

**Comment by mk01** [comment]
are you both aware of the 'global' libcurl & curl issues, right ? making playing streams not working at all...
it looks like OE started panic only now, but for imx6(jessie) we provide older version 7.37 for months via XBian apt repo (in imx6-jessie).

at that time RPI was (due old wheezy libs) unaffected, with curl somwhere around 7.24. now looking at raspbian inventories, 7.38 (broken one) was added middle Jan-2015.

and I'm just wondering what makes more sense ... if code being build since Dec-2014 suddenly goes mad, or upstream pushed broken lib in Jan which hits live systems around now?

I don't have evidence to prove option1 and don't have res to check the other. please do so by checking if *curl* installed is above 7.37. if yes, then downgrade, restart xbmc, retest. in case this resolves the issue, just push *curl* related .deb files into main/rpi-wheezy. apt preference with pins already contains that 
```
Package: libcurl3 curl libcurl3-gnutls
Pin: release o=XBian
Pin-Priority: 1001
```
if wheezy has different names (99% it don't), ADD to the list and repush -repo package.

**Comment by f1vefour** [comment]
We are on 7.26.0 on Pi 2

**Comment by mk01** [comment]
@f1vefour 

so the others (http://archive.raspbian.org/raspbian/pool/main/c/curl/) are not yet put into lists ??? or is Rasobian MIXING pool dirs one over the other (from all 'codenames') they clone ?

**Comment by f1vefour** [comment]
xbian@xbian ~ $ apt-cache policy libcurl3
libcurl3:
  Installed: 7.26.0-1+wheezy12
  Candidate: 7.26.0-1+wheezy12
  Package pin: (not found)
  Version table:
 *** 7.26.0-1+wheezy12 1001
        500 http://mirrordirector.raspbian.org/raspbian/ wheezy/main armhf Packages
        100 /var/lib/dpkg/status
xbian@xbian ~ $

**Comment by CurlyMoo** [comment]
The pacakge file only consists of 7.26.0-1
http://mirrordirector.raspbian.org/raspbian/dists/wheezy/main/binary-armhf/Packages

**Comment by mk01** [comment]
libproxy patch then it is

**Comment by CurlyMoo** [comment]
Is the fault or?

**Comment by mk01** [comment]
how the mr. spock is always saying it?
```
If you eliminate the impossible, whatever remains, however improbable, must be the truth. 
```

of course we get it confirmed with the next build, or ?

**Comment by f1vefour** [comment]
I had an idea. Upstream kodi was patched to work with updated libcurl, so I added jessie to my repos and updated (everything updated without issue) but apparently my idea was wrong as it didn't work.

The interesting thing I learned is adding jessie updated 200+ packages without breaking anything that is see, so maybe it won't be hard to transition to a jessie base.

**Comment by mk01** [comment]
@f1vefour 

actually it is because we did it working. imx6 is jessie, and while targeting to have MOST of the code/packages shared/reusable no matter what would be target distro/system, those have been updated over the year to work like that. 
meaning - updating rpi / wheezy to jessie is (from the partical .deb point of view) the same as to have it installed on cubox. 

this still isn't fully proving that we can build rpi-jessie error free - probably some tuning of debs currently in the category rpi-wheezy will be needed.I have seen that on debs prepared 1y ago directly for Jessie at that time - their dependency was installed at install time, over the time the needed packages disappeared from Jessie, but if they are not replaced by a conflicting package or similar, apt has no reason to remove them from system too (as still needed and despite their disappearance from apt inventories). 

the same could happen for you - your new jessie maybe keeping some leftovers from wheezy - not affecting new jessie, but still supporting installed XBian debs compiled and linked agains wheezy.

(and the biggest part wasn't deb dependencies actually - but making all the XBian tools / code / helpers to deal with different configs, system folder structure etc.). 
(((now and then curly is still finding some parts, not frequently used and not working on one or the other))).

**Pull request merged**
