### PR TITLE
Building addons provided in project/cmake/addons for rpi-nightly and imx...

### PR DESCRIPTION
**Pull request by mkreisl**
...6-nightly

### CODE REVIEW

**Comment by mk01** [comment]
just please check the comments, push, I will merge !

**Comment by mkreisl** [comment]
Hmmm, I don't understand the neccesary of ":" at the end of line, because IMHO the second operation is only executed if first operation is true. So, theoretically, it never fails

**Comment by mkreisl** [comment]
but anyway, I addet the three ` || :`

**Comment by mk01** [comment]
@mkreisl 

but command line with && and || is processed exactly according the rules of boolean algebra and like with * (multiplication) and + there is commutativity.

so with && there is no second operation alone. if first evaluates false, whole line is false -> script fails

try yourself:
```
false && true \
&& echo "ALLOK" || echo "FAILED"
```

where 1st line simulates non existing directory.

**Comment by mkreisl** [comment]
Ok, I will keep it in mind. I only can't understand why this script run without producing an error. And believe me, I ran this many many times ....

**Comment by mk01** [comment]
@mkreisl 

good question. it is because 
https://github.com/xbianonpi/xbian/blob/master/common.functions#L149

the +e did I myself, probably was testing/debugging something and on commit forgot to revert.
a61f4af5ee242ce594de19348a496567af26c215

I will read the above discussion with @CurlyMoo if is not related and will remove the +e (so scripts -e will come to effect).
basically we very want that, any automated schedules are loosing point if they don't stop on errors.

thanks for the corrections!

**Comment by CurlyMoo** [comment]
What discussion?

**Comment by mk01** [comment]
in commit a61f4af5ee242ce594de19348a496567af26c215

I put +e to run hooks. I think I kept it there after some debugging of the code ... or was it related in any of the discussion around img generation and it's errors ?

**Comment by mkreisl** [comment]
@mk01 
The thing with ` || :` doesn't go out of my head. 
I tested again, wiped out the working directory, put a `set -e` to the beginning of the script and let him build xbmc package w/o the three ` || :` - it runs through to the end.
So, I asked google and found such answers like this: http://unix.stackexchange.com/questions/24684/confusing-use-of-and-operators (post 27) or this http://wiki.ubuntuusers.de/Shell/Operatoren (in german)

**Comment by mk01** [comment]
o yes, && is evaluated as closed chain which "just" gets interrupted by an error in it.
so in this particular case it is not required and finally true is assured by -f (on rm).
- old habits are old safe habits


but I came to comment back because only now spotted the comment you made https://github.com/mkreisl/xbian-package-xbmc/blob/281ad2fafee82a6c071aa6c854d294916f5f2cda/hooks.d/pre-build.d/configure-addons#L2 
despite the actual single-command which triggers the script, work flow order is the same.

btw if you want , feel free to create post-configure.d (or XYZ if needed) like this -> https://github.com/xbianonpi/xbian/blob/master/build.package#L40

**Comment by mkreisl** [comment]
Yes, I already created a post-configure.d folder, but do_prep() doesn't make the call to it and I didn't want to change too much (I only changed this for testing on my local disk)

**Comment by mkreisl** [comment]
Btw, do you already work on libcec 3.0? The new xbmc sources you just commited (rpi-nightly) requires 3.0 now and I already made some experiments building a new package

**Comment by mk01** [comment]
when I was consolidating the RPI & IMX6 tree (our tree) - I by mistake took 3.0 branch as upstream. 
I'm not a huge fan of cmake :-/

can you register at jenkins.xbian.org ?

**Comment by CurlyMoo** [comment]
> I'm not a huge fan of cmake :-/

WTF :astonished:

**Comment by mk01** [comment]
@CurlyMoo 
i hate it :)

**Comment by CurlyMoo** [comment]
You're just a cmake noob.

**Comment by mkreisl** [comment]
@mk01 
Yes, I registered now on jenkins - but what is it? I get Access denied.
I have no problem with cmake - I know very little about thees kind of tools, so it makes no difference if cmake or not ;-). But the Kodi team seams a big fan of cmake ...

**Comment by CurlyMoo** [comment]
I'm a big fan of it as well. I use it for all my projects.

**Comment by mk01** [comment]
@CurlyMoo 
yes. for me it is enough as reason.
:)

**Comment by mk01** [comment]
@mkreisl 

then you can rebase the xbian-sources-cec on 3.0

**Comment by mkreisl** [comment]
Now it works, but before I do anything with it I have to learn more about this ...

**Comment by mkreisl** [comment]
@mk01
So, how do I use your Jenkins environment. It is hard to use is w/o docs, I assume or hope there are some threads about this in your forum, but unfortunately I have no access rights for this.
I found this thread https://github.com/xbianonpi/xbian-package-firmware/pull/1 and there @CurlyMoo refers to a thread inside the forum http://forum.xbian.org/thread-2682.html which I cat not access.
So, what do I have to do to get more informed?
Btw, I finished work for xbian-package-cec (rpi and i.MX6) for version 3 is ready to test

**Comment by CurlyMoo** [comment]
I think the highest priority is fixing the RPi2 and RPi images. All work is pretty useless when users don't have the ability to actually use it.

**Comment by mkreisl** [comment]
@CurlyMoo 
Yes, I agree. In your point of view you are right.
But what are the main problems? IMHO the main problem is Helix, my problems began after changing from Gotham to Helix (I started with 14.1). However, with 14.2 it was nearly impossible to get a stable system so I made the decision for me to make a step forward -  throw Helix away and go directly to 15.0. And what should I say, it works much much better then Helix and for a beta version it runs perfect. 
So, I don't believe it makes sense to put much work into Helix to make it work (backporting from 15) which will be obsolete in a few month. But again, this is my opinion and I don't expect that you argree with me

**Comment by CurlyMoo** [comment]
I actually mean automatic image generation that doesn't work anymore because of wrecked dependencies. I already mailed @mk01 about it several time but after a 1.5 month we still don't have new RPi images.

**Comment by mkreisl** [comment]
Ah, I understand. And I already noticed that some (or all?) building jobs are paused

**Comment by mkreisl** [comment]
@CurlyMoo 
Hmm, this is a very bad situation. I don't know the reasons for this and I am not sure that I want to know more about this. But if I can help please let me know

**Comment by CurlyMoo** [comment]
You can try building a full image locally by following the image creation guide here on the wiki.

**Comment by mkreisl** [comment]
Seriously, you can't do that?
Making sure that I don't misunderstand you - you mean this page http://wiki.xbian.org/doku.php/create_image?
Ok, I did this, no problem. Here is my result: http://www.mediafire.com/download/h1cjlu8u58duda6/XBian_2015.05.17_rpi.img.gz
Written back to sd-card and boot from it - no problem

**Comment by CurlyMoo** [comment]
Can you try to create the RPi2 image as well just to see if it succeeded without issues.

**Comment by mkreisl** [comment]
Ah, ok
I just made the images for RPi and RPi2 - no issues. Only a strange message nearly at the and appeared, but the build process is ok. I investigated this message and made a small change in build.img, but this has no effect in building the image.
Had to use a Ubuntu 14.04 because unfortunately my native buildsystem does not have btrfs support

**Comment by CurlyMoo** [comment]
Can you post both images for me to investigate?

**Comment by mkreisl** [comment]
Yes, of course. It is just in progress takes one hour.
I've burned already RPi1, seems ok (Kodi 14.2 Mai 7) comes up.

**Comment by CurlyMoo** [comment]
Can you maybe join me on IRC in 5 to 10 minutes from now?

**Comment by mkreisl** [comment]
I am online

**Comment by mkreisl** [comment]
@CurlyMoo 
Success!
Here are my local builds:
http://www.mediafire.com/download/tqn5cwe0tnd1p7f/XBian_2015.05.18_rpi.img.gz
http://www.mediafire.com/download/1ajwmswsdsvbazg/XBian_2015.05.18_rpi2.img.gz
and the images on your server -- you know where they are
I downloaded the RPi1 image and burned it, seems ok (Kodi 14.2 May 7) comes up.

**Comment by CurlyMoo** [comment]
Let's meet on IRC again today.

**Pull request merged**
